language: minimal

services:
  - docker

env:
- PYTHON_IMAGE=python:3.5 POSTGRES_IMAGE=postgres:9.6
- PYTHON_IMAGE=python:3.6 POSTGRES_IMAGE=postgres:9.6
- PYTHON_IMAGE=python:3.7 POSTGRES_IMAGE=postgres:9.6
- PYTHON_IMAGE=python:3.8 POSTGRES_IMAGE=postgres:9.6

jobs:
  allow_failures:
    - env: PYTHON_IMAGE=python:3.8

before_script:
  - ./scripts/ci/build-docker-env.sh

script:
  - ./scripts/ci/run-tests-with-docker.sh

after_success:
  # Report coverage results to codecov.io
  - bash <(curl -s https://codecov.io/bash)
