name: OAR3 - generates debian packages
on:
  push:
    branches:
      - "release-ci"
    tags:
      - 3.*

jobs:
    Generate-Debian-Packages:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Connect to dockerhub
          run: echo $DOCKERTOKEN | docker login --username ${DOCKERUSER} --password-stdin
          env:
            DOCKERUSER: ${{ secrets.DOCKERUSER }}
            DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}
        - name: Generate the debian packages
          run: cd ./misc/deb-gen && ./build-deb.sh
        # Upload artifact
        - name: generated files
          run: tree misc
        - uses: actions/upload-artifact@v2
          with:
            name: debian-packages
            path: ./misc/deb-gen/build/**.deb
    build:
      runs-on: ubuntu-latest
      needs: [Run-Tests-On-Docker, Generate-Debian-Packages]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/download-artifact@v3
          with:
            name: debian-packages
        - name: debug
          run: tree
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')