name: OAR3 - generates debian packages
on:
  push:
    branches:
      - "release-ci"
    tags:
      - 3.*

jobs:
    Generate-debian-packages:
      env:
        OUTPUT: debian-packages.tar.gz
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
          # Connect to docker to have user-base docker rate limit instead of by ip
        - name: Connect to dockerhub
          run: echo $DOCKERTOKEN | docker login --username ${DOCKERUSER} --password-stdin
          env:
            DOCKERUSER: ${{ secrets.DOCKERUSER }}
            DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}
        - name: Generate the debian packages
          run: cd ./misc/deb-gen && ./build-deb.sh
        - name: Create a compressed archive
          run: tar -czf ${{ env.OUTPUT }}  misc/deb-gen/build/*.deb
        - uses: actions/upload-artifact@v2
          with:
            name: ${{ env.OUTPUT }}
            path: ${{ env.OUTPUT }}
    Generate-Release:
      runs-on: ubuntu-latest
      needs: Generate-Debian-Packages
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/download-artifact@v3
          with:
            name: debian-packages
        - name: debug
          run: tree
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: debian-packages.tar.gz